// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.NewFolder1;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20250430120006_AddNewChanges")]
    partial class AddNewChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.entity.general", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("general");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "romance"
                        });
                });

            modelBuilder.Entity("WebApplication1.entity.movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDa")
                        .HasColumnType("date");

                    b.Property<int>("generalid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("generalid");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "inception",
                            Price = 12,
                            ReleaseDa = new DateOnly(2003, 2, 3),
                            generalid = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "dark host",
                            Price = 15,
                            ReleaseDa = new DateOnly(2006, 3, 7),
                            generalid = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "the matrix",
                            Price = 16,
                            ReleaseDa = new DateOnly(2008, 8, 5),
                            generalid = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "the lord",
                            Price = 18,
                            ReleaseDa = new DateOnly(2009, 3, 8),
                            generalid = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "god",
                            Price = 20,
                            ReleaseDa = new DateOnly(2004, 6, 9),
                            generalid = 5
                        });
                });

            modelBuilder.Entity("WebApplication1.entity.movie", b =>
                {
                    b.HasOne("WebApplication1.entity.general", "general")
                        .WithMany()
                        .HasForeignKey("generalid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("general");
                });
#pragma warning restore 612, 618
        }
    }
}
