// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Entity.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("General_Id")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            General_Id = 1,
                            Name = "inception",
                            Price = 12,
                            ReleaseDate = new DateOnly(2003, 2, 3)
                        },
                        new
                        {
                            Id = 2,
                            General_Id = 2,
                            Name = "dark host",
                            Price = 15,
                            ReleaseDate = new DateOnly(2006, 3, 7)
                        },
                        new
                        {
                            Id = 3,
                            General_Id = 3,
                            Name = "the matrix",
                            Price = 16,
                            ReleaseDate = new DateOnly(2008, 8, 5)
                        },
                        new
                        {
                            Id = 4,
                            General_Id = 4,
                            Name = "the lord",
                            Price = 18,
                            ReleaseDate = new DateOnly(2009, 3, 8)
                        },
                        new
                        {
                            Id = 5,
                            General_Id = 5,
                            Name = "god",
                            Price = 20,
                            ReleaseDate = new DateOnly(2004, 6, 9)
                        });
                });

            modelBuilder.Entity("WebApplication1.entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sci-fi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "romance"
                        });
                });

            modelBuilder.Entity("WebApplication1.Entity.Movie", b =>
                {
                    b.HasOne("WebApplication1.entity.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
